---
# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python
build:
  os: ubuntu-24.04
  tools:
    python: "miniconda-latest"
  commands:
    # because we are overriding the build commands, we need to setup the environment ourselves
    - cat docs/environment.yml
    - conda env create --quiet --name $READTHEDOCS_VERSION --file docs/environment.yml
    - cmake -B build -S .
    - cmake --build build --target docs

# using conda, we can get newer doxygen and graphviz than ubuntu provide
# https://github.com/readthedocs/readthedocs.org/issues/8151#issuecomment-890359661
conda:
  environment: docs/environment.yml

submodules:
  include: all
  recursive: true
